default:
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e ".[dev,test]"

stages:
  - lint
  - typecheck
  - test
  - docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

lint:
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - python -m pip install --upgrade pip
    - pip install -e ".[dev,test]"
  stage: lint
  script:
    - pip install pre-commit
    - pre-commit run --all-files --show-diff-on-failure

typecheck:
  stage: typecheck
  script:
    - mypy

test:
  stage: test
  script:
    - pytest -q --cov=dstoolbox --cov-report=term-missing --cov-report=xml
  coverage: '/(?i)total.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  stage: docs
  script:
    - pip install -e ".[docs]"
    - bash scripts/build_docs.sh
    - mv docs/api public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

