
mssql_servers:
  dev:
    db_server: localhost\SQLEXPRESS
    database: TestDB  # Optional
    trusted_connection: true  # Uses Windows auth
    trust_server_certificate: true

  prod:
    db_server: prod-sql-server.company.com
    database: ProductionDB
    trusted_connection: true  # Uses Windows auth
    trust_server_certificate: true

postgresql_servers:
  local_machine:
    host: localhost
    port: 5431
    user: xxxx
    password: xxxx
    database: xxx

  Ec2_machine:
    host: xxxx.rds.amazonaws.com
    port: 5432
    user: xxx
    password: xxxx
    database: xxx

# xxx_server:
#   host: xxx.company.com #localhost
#   port: 1433
#   user: xxx_user
#   password: xxx_pass
#   database: xxx_db

# key_vault_dictS : 
# ###Azure blob storages:(It is name of storage account name for azure blob storage aswell)
#   xxxxx:  
#     key_vault_name : ****
#     secret_name    : ****

# ###deltaTable:
#   deltaTable: 
#     key_vault_name : ****
#     secret_name    : ****

# ###Webapi:
#   webapi:         ##used by get_interpolated_pi_data and get_raw_pi_data functions:
#     secret_name    : ****
#     key_vault_name : ****

# ###azure Synapse:
#   azure_synapse: 
#     key_vault_name: ****
#     secret_name   : ****

# synapse_cred_dict: 
#   hostname      : ****
#   database      : ****
#   username      : ****
#   driver_odbc   : ****
#   driver        : ****
#   port          : ****

# azure_ml_appID:
#   ****

# KV_access_local:
#   secret_TenantID               : ****
#   secret_ClientID__prd          : ****
#   secret_ClientSecret__Prd      : ****

# pi_server:
#   url               : *****
#   grant_type        : *****
#   client_id         : *****
#   scope             : *****